### ISSUE TITLE
Get function

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/cookieman#12]
Most of the time I don't care that there is more than one of the same cookie or not. This probably only occurs if there has been some setup issue.

I think in a load of code I am writing
```js
function getCookie (name) {
  var cookies = cm.get(name)
  if (cookies.length) return cookies[0].value
}
```

It would be nice to have a simple method exposed as `getFirst` or something. Ideally `get` would get the first occurrence and `getAll` would get all of them but I guess an API change would be a pain.

**Comment by alanclarke** [comment]
+1 defo, what about:

```
cm.val(name) // gets first value
cm.val(name, value, opts) // sets cookie
```

**Comment by roberttod** [comment]
Maybe just
```js
cm.val(name) // gets first value
```

don't see a reason to change the set API.

**Comment by KidkArolis** [comment]
Why not `getFirst` then? You'd then have `get`, `set` and `getFirst`.

But I think Alan's suggestion was that get/set would essentially be
deprecated (but available forever) and `val` is the new recommended,
simpler API. Except for things like .. .val('foo', x) where x is undefined,
which then doesn't set (clear the cookie), but just gets it. You know what
I mean?

**Comment by wbecker** [comment]
What if there are two cookies though? You read one, you write it back, if you read it again, is that the same one you will get back or is it another one? 

Maybe it should either try to fix things up if there are multiple cookies, or throw an exception? Otherwise you could keep writing to the other cookie, and every time you try to read you won't get the same value back and then someone will see a popup over and over again until they throw their mouse at the screen.

Are any CSEs still writing those cookie fixing scripts? :crying_cat_face: :gun:  

BTW, Hi Guys! Anyone up for a Katsu?

**Comment by peterfronc** [comment]
Sounds like a good idea!

**Comment by alanclarke** [comment]
hey @wbecker!

so some more thoughts on this:

- i think one thing that differentiates cookieman from other cookie libs is that its api is not a lie, as in, the fact that it doesn't pretend that there can't be two cookies with the same name is part of its raison d'etre
- fixing things up is an interesting idea and could be a cool feature but it might be a bit magical? also it would make reading have side effects, also it would make reading more expensive, and actually turns out cookie reading and writing is atomic, blocking, expensive and has a big impact on perf
- getFirst suggests it is a shortcut for doing this:
```js
function getFirst (name) {
   return cm.get(name)[0]
}
```
i.e. returning a cookieman representation of a cookie, whereas ``` cm.val ```  implies that the value itself is returned, i.e. it goes further and extracts the actual value, or an empty string if the cookie exists without a value, or null if the cookie didn't exist
```js
var value = cm.val('cookie')
```
so it is probs more convenient?

**Comment by alanclarke** [comment]
![defo](http://www.justonecookbook.com/wp-content/uploads/2014/06/Katsu-Curry.jpg)

**Comment by activars** [comment]
Good idea

**Comment by wbecker** [comment]
http://i.imgur.com/nLsaHr9.jpg

**Comment by wbecker** [comment]
Can probably close this off now
![nlsahr9](https://cloud.githubusercontent.com/assets/348044/13989388/07d3fd14-f108-11e5-8160-ca449760688b.jpg)

**Comment by roberttod** [comment]
:cry:

**Comment by samuelfullerthomas** [comment]
Addressed in [this pull request](https://github.com/QubitProducts/cookieman/pull/13).

**Comment by roberttod** [comment]
@samuelfullerthomas, close the issue when the PR is merged 😑

**Comment by KwanMan** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by KwanMan** [comment]
I like having context to PRs
